geometry_msgs/Vector3 pos    # Position (x, y, z) in map coordinates (m)
geometry_msgs/Vector3 vel_world    # Linear velocity (m/s)
geometry_msgs/Vector3 rpy    # Orientation (roll, pitch, yaw) in radians
geometry_msgs/Vector3 vel    # Linear velocity (m/s)
geometry_msgs/Vector3 acc    # Linear acceleration (m/s^2)
geometry_msgs/Vector3 gyro   # angular velocity (rad/s)
int32[] reserved_int
float64[] reserved_ft
uint32[] reserved_uint
